FROM ccpr.cocktailcloud.io/docker.io/library/eclipse-temurin:17.0.11_9-jdk-alpine
COPY target/api-gateway-1.0-SNAPSHOT.jar api-gateway-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","api-gateway-1.0-SNAPSHOT.jar"]
