FROM ccpr.cocktailcloud.io/docker.io/library/eclipse-temurin:17.0.11_9-jdk-alpine
COPY target/eureka-server-1.0-SNAPSHOT.jar eureka-server-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","eureka-server-1.0-SNAPSHOT.jar"]
