FROM ccpr.cocktailcloud.io/docker.io/library/eclipse-temurin:17.0.11_9-jdk-alpine
COPY target/movie-service-1.0-SNAPSHOT.jar movie-service-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","movie-service-1.0-SNAPSHOT.jar"]
