FROM ccpr.cocktailcloud.io/docker.io/library/eclipse-temurin:17.0.11_9-jdk-alpine
COPY target/movieService-1.0-SNAPSHOT.jar movieService-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","movieService-1.0-SNAPSHOT.jar"]
