FROM ccpr.cocktailcloud.io/docker.io/library/eclipse-temurin:17.0.11_9-jdk-alpine
COPY target/user-service-1.0-SNAPSHOT.jar user-service-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","user-service-1.0-SNAPSHOT.jar"]
